/**
 * Mapster — Rain Weather Behavior
 * Physics + visuals for the 'Rain' effect. Rendered as fast vertical streaks
 * (the streak sprite is generated by weatherManager). Particles live in a box
 * ~30 units wide centered on the player; they fall fast and recycle to the top.
 */
const RainWeather = {
    id: 'rain',
    name: 'Heavy Rain',

    // Visual Properties (weatherManager scales size by intensity).
    size: 0.6,           // streak sprite base size — readable, not huge
    color: 0xbfd4ff,     // cool, slightly blue-white rain
    texturePath: null,   // null = use the procedural streak sprite

    // Physics. positions is a flat [x,y,z, x,y,z, ...] Float32Array, LOCAL to
    // the system (which is centered on the player). Box spans roughly -15..+15.
    update: function (positions, time, dt) {
        const TOP = 18, BOTTOM = -4, SPAN = 30;
        for (let i = 0; i < positions.length; i += 3) {
            positions[i + 1] -= 24 * dt;            // fast straight fall (Y)
            positions[i]     += 2.2 * dt;           // light slanting wind (X)
            if (positions[i + 1] < BOTTOM) {
                positions[i + 1] = TOP;             // recycle to the top
                positions[i]     = (Math.random() - 0.5) * SPAN;
                positions[i + 2] = (Math.random() - 0.5) * SPAN;
            }
        }
    }
};
if (typeof module !== 'undefined' && module.exports) { module.exports = RainWeather; }
else if (typeof window !== 'undefined') { window.RainWeather = RainWeather; }
