/**
 * Mapster — Snow Weather Behavior
 * Physics + visuals for the 'Snow' effect. Rendered as soft round flakes (the
 * flake sprite is generated by weatherManager). Gentle fall with a sideways
 * sway so flakes meander instead of dropping straight.
 */
const SnowWeather = {
    id: 'snow',
    name: 'Gentle Snow',

    size: 0.45,          // soft flake base size
    color: 0xffffff,
    texturePath: null,   // null = use the procedural flake sprite

    update: function (positions, time, dt) {
        const TOP = 18, BOTTOM = -4, SPAN = 30;
        for (let i = 0; i < positions.length; i += 3) {
            positions[i + 1] -= 3.0 * dt;                                  // gentle fall (Y)
            positions[i]     += Math.sin(time * 0.6 + i * 0.3) * 0.6 * dt; // meandering sway (X)
            positions[i + 2] += Math.cos(time * 0.5 + i * 0.2) * 0.4 * dt; // slight Z drift
            if (positions[i + 1] < BOTTOM) {
                positions[i + 1] = TOP;
                positions[i]     = (Math.random() - 0.5) * SPAN;
                positions[i + 2] = (Math.random() - 0.5) * SPAN;
            }
        }
    }
};
if (typeof module !== 'undefined' && module.exports) { module.exports = SnowWeather; }
else if (typeof window !== 'undefined') { window.SnowWeather = SnowWeather; }
