/* ============================================================================
 *  core/demo.js  —  WEB-DEMO LAYER  (loaded ONLY by the demo build)
 * ----------------------------------------------------------------------------
 *  The public web demo (demo/index.html, generated by tools/build_demo.js) is
 *  the opening of the game: splash → title → intro crawl → character creation
 *  → the Day-1 wake-up → the parking-lot arrival → the tutorial rooms → the
 *  first-shift lobby. It's meant to be EMBEDDED (an <iframe> on a Neocities
 *  page), so this file adds the few things that only make sense there:
 *
 *   1. CLICK-TO-PLAY GATE — an iframe gets no keyboard focus until it's
 *      clicked, and browsers block audio until a user gesture. So the demo
 *      opens on a "click to play" card; the click both focuses the frame and
 *      unlocks sound, THEN the Brickroad splash + title theme start.
 *      midmulti.html's boot call is rewritten by the build to go through
 *      MMDemo.gate(start).
 *   2. END OF DEMO — FIRST_SHIFT is where the built game currently stops. In
 *      the demo, finishing it ("wait" / "clock in" / …) goes to a proper
 *      Screens.DEMO_END card (play again / back to title) instead of a flash.
 *   3. GUARDS — Continue/Load resume at the Day-1 morning instead of the full
 *      game's in-development lobby hub (GAME_PLACEHOLDER); minigames aren't
 *      shipped with the demo, so openMinigame() explains that instead of
 *      loading a missing page. (The debug room is hidden via IS_DEMO_BUILD()
 *      checks in settings.js / debugroom.js.)
 *
 *  The full game never loads this file (midmulti.html doesn't list it), and
 *  window.MM_BUILD.demo is set by the demo page before any script runs.
 *
 *  Load order: after core/tutorial.js + core/debugroom.js (it wraps screens
 *  and functions they define) and before the boot <script> in the page.
 *  HOW TO MODIFY: the gate card's text/styling is in gate() below; the end
 *  card's copy is in Screens.DEMO_END.render().
 * ========================================================================== */
(function () {
  'use strict';
  if (!(window.MM_BUILD && window.MM_BUILD.demo)) return;   // full game: do nothing

  // ── 1. CLICK-TO-PLAY GATE ────────────────────────────────────────────────
  // Shows a full-page card over the (blank) title canvas. One click / key /
  // tap removes it and calls start(). Touch-only devices get a gentle note
  // that the demo needs a keyboard (it's typed commands + WASD), but can still
  // look around the title screen.
  const GATE_CSS =
    '#demo-gate{position:fixed;inset:0;z-index:9999;display:flex;align-items:center;justify-content:center;' +
      'background:radial-gradient(ellipse at center,#141a2c 0%,#05060a 70%);cursor:pointer;' +
      'font-family:"GrandeRetro","GrandeTerm","Courier New",monospace;color:#e8d9a8;text-align:center;' +
      'transition:opacity .25s ease;padding:16px;box-sizing:border-box;}' +
    '#demo-gate.dg-out{opacity:0;}' +
    '#demo-gate:focus{outline:none;}' +
    '#demo-gate .dg-inner{border:3px double #c9a227;padding:clamp(16px,4vw,36px) clamp(18px,6vw,56px);' +
      'box-shadow:0 0 0 6px #05060a,0 0 0 8px #6b2a6f,0 0 40px rgba(201,162,39,.25);max-width:92vw;}' +
    '#demo-gate .dg-kicker{font-size:clamp(10px,1.6vw,13px);letter-spacing:.4em;color:#9fd17a;opacity:.8;margin-bottom:14px;}' +
    '#demo-gate .dg-title{font-size:clamp(28px,7vw,64px);line-height:.95;color:#f1c84b;letter-spacing:.04em;' +
      'text-shadow:0 0 12px rgba(241,200,75,.45),3px 3px 0 #5a1d1d;}' +
    '#demo-gate .dg-title span{display:block;font-size:.42em;color:#e8d9a8;letter-spacing:.3em;margin:.35em 0 .2em;text-shadow:none;}' +
    '#demo-gate .dg-play{margin-top:clamp(16px,4vh,30px);font-size:clamp(16px,3vw,26px);color:#7dff9a;' +
      'animation:dg-pulse 1.6s ease-in-out infinite;}' +
    '#demo-gate .dg-sub{margin-top:14px;font-size:clamp(11px,1.7vw,14px);color:#b8b09a;}' +
    '#demo-gate .dg-keys{margin-top:6px;font-size:clamp(10px,1.5vw,13px);color:#7d7a70;}' +
    '#demo-gate .dg-keys b{color:#ff9a7a;font-weight:normal;}' +
    '@keyframes dg-pulse{0%,100%{opacity:.55}50%{opacity:1}}' +
    '@media (prefers-reduced-motion: reduce){#demo-gate .dg-play{animation:none}}';

  function gate(start) {
    const style = document.createElement('style');
    style.textContent = GATE_CSS;
    document.head.appendChild(style);
    const touchOnly = (typeof matchMedia === 'function') && matchMedia('(hover: none) and (pointer: coarse)').matches;
    const card = document.createElement('div');
    card.id = 'demo-gate';
    card.setAttribute('role', 'button');
    card.setAttribute('tabindex', '0');
    card.setAttribute('aria-label', 'Click to play Midnight at the Multiplex');
    card.innerHTML =
      '<div class="dg-inner">' +
        '<div class="dg-kicker">BRICKROAD PRESENTS</div>' +
        '<div class="dg-title">MIDNIGHT<span>AT THE</span>MULTIPLEX</div>' +
        '<div class="dg-play">▶ CLICK TO PLAY</div>' +
        '<div class="dg-sub">Web demo · the opening of the game · about 15–20 minutes</div>' +
        '<div class="dg-keys">Keyboard + mouse · sound on · ' +
          (touchOnly ? '<b>needs a physical keyboard</b>' : 'press F11 for fullscreen') + '</div>' +
      '</div>';
    document.body.appendChild(card);
    let started = false;
    const go = (e) => {
      if (started) return;
      if (e && e.type === 'keydown' && (e.key === 'Tab' || e.key === 'Shift')) return;   // let people tab past an embed
      started = true;
      if (e && e.preventDefault) e.preventDefault();
      if (e && e.stopPropagation) e.stopPropagation();
      card.removeEventListener('click', go);
      window.removeEventListener('keydown', go, true);
      card.classList.add('dg-out');
      setTimeout(() => card.remove(), 260);
      try { window.focus(); } catch (err) {}
      try { start(); } catch (err) { console.error(err); }
      armFocusPause();   // from now on, losing focus shows "Paused — click to resume"
    };
    card.addEventListener('click', go);
    window.addEventListener('keydown', go, true);
  }

  // ── 2. END OF DEMO ───────────────────────────────────────────────────────
  // FIRST_SHIFT's "finish" verbs route here. The first time FIRST_SHIFT draws,
  // a one-line hint tells the player how to wrap up.
  const FS = Screens.FIRST_SHIFT;
  if (FS) {
    const _render = FS.render, _handle = FS.handle;
    FS.render = function () {
      if (!State._demoEndHinted) {
        State._demoEndHinted = true;
        setTimeout(() => { try { flash('That’s the end of the demo — look around, then type  wait  to wrap up.'); } catch (e) {} }, 400);
      }
      return _render.apply(this, arguments);
    };
    FS.handle = function (text) {
      const t = (text || '').toLowerCase().trim();
      if (t === 'wait' || t === 'clock in' || t === 'start' || t === 'work' || t === 'go' || t === 'continue' || t === 'end' || t === 'next') {
        sfx.confirm(); State._demoEndHinted = false; goto('DEMO_END'); return;
      }
      if (t === 'help' || t === '?') { flash('End of the demo. Try:  look · wait.'); return; }
      return _handle.apply(this, arguments);
    };
  }

  Screens.DEMO_END = {
    // cursor/click/arrow driven, like TUTORIAL_OFFER (↑↓ or ←→ pick, Enter
    // confirms, or click). "again" mirrors the title menu's NEW GAME path.
    _acts: [
      { act: 'again', label: 'PLAY AGAIN — make a new character' },
      { act: 'title', label: 'TITLE SCREEN' },
    ],
    render() {
      if (State._demoEndCur == null) State._demoEndCur = 0;
      const btns = this._acts.map((b, i) => {
        const foc = i === State._demoEndCur;
        return '<span class="cg-btn cg-act' + (foc ? ' cg-row-focus' : '') + '" data-cg="' + b.act + '">' + (foc ? '▸' : ' ') + '[ ' + b.label + ' ]</span>';
      });
      const who = (State.character && State.character.name) ? State.character.name : 'You';
      return header('END OF THE DEMO') + '\n' + [
        '',
        '   Thanks for playing the opening of ' + span('accent', 'MIDNIGHT AT THE MULTIPLEX') + '.',
        '',
        '   ' + span('stat-name', who + ' made it through the first morning, the parking lot, and the'),
        '   ' + span('stat-name', 'tutorial rooms. The first conversation — and everything after it: the'),
        '   ' + span('stat-name', 'shifts, the cliques, the Thursday-night previews, and The Horrors —'),
        '   ' + span('stat-name', 'is still being built.'),
        '',
        '   ' + span('ok', 'A 1999 movie-theater life-sim by Brickroad.'),
        '',
        '   ' + btns[0],
        '   ' + btns[1],
        '',
        '   ' + span('stat-name', '↑↓ / ←→ choose · Enter confirms · or click'),
      ].join('\n');
    },
    onKey(e) {
      if (State._demoEndCur == null) State._demoEndCur = 0;
      const n = this._acts.length, k = e.key;
      if (k === 'ArrowUp' || k === 'ArrowLeft' || k === 'w' || k === 'a') { State._demoEndCur = (State._demoEndCur - 1 + n) % n; sfx.type(); render(); return true; }
      if (k === 'ArrowDown' || k === 'ArrowRight' || k === 's' || k === 'd') { State._demoEndCur = (State._demoEndCur + 1) % n; sfx.type(); render(); return true; }
      if (k === 'Enter' || k === ' ') { this.onClick(this._acts[State._demoEndCur].act); return true; }
      return false;
    },
    onClick(action) {
      State._demoEndCur = 0;
      if (action === 'again') {
        sfx.confirm();
        resetRunState();                      // same as the title menu's 1 NEW GAME
        State.character = blankCharacter();
        goto('INTRO');
        return;
      }
      if (action === 'title') { sfx.back(); MultiplexGame.hide(); return; }
    },
    handle(text) {
      const t = (text || '').trim().toLowerCase();
      if (t === 'again' || t === 'new' || t === 'play' || t === 'yes') { this.onClick('again'); return; }
      if (t === 'title' || t === 'back' || t === 'quit' || t === 'menu') { this.onClick('title'); return; }
      sfx.error(); flash('↑↓ choose, Enter confirms, or click.');
    },
  };

  // ── 3. GUARDS ────────────────────────────────────────────────────────────
  // CONTINUE / LOAD → the start of Day 1. Saves record the character + world
  // but not the screen, and every load path (title "Continue", the LOAD picker,
  // the ESC menu) lands on GAME_PLACEHOLDER — the full game's in-development
  // lobby hub, which isn't part of the demo (and advertises the dev tools). In
  // the demo, redirect it to the Day-1 morning with the loaded character; the
  // only save point is chargen's "start", so that's where they'd resume anyway.
  if (Screens.GAME_PLACEHOLDER) {
    Screens.GAME_PLACEHOLDER.render = function () {
      State._wake = null;            // wakeInit() re-runs: 6:35 AM, in bed
      State.screen = 'WAKE_UP';
      return Screens.WAKE_UP.render();
    };
  }

  // Minigame pages aren't part of the demo package.
  window.openMinigame = function () {
    try { sfx.error(); flash('Minigames aren’t in the web demo yet.'); } catch (e) {}
  };

  // ── 4. FOCUS PAUSE ───────────────────────────────────────────────────────
  // An embedded demo silently stops receiving keys the moment the player clicks
  // anywhere on the host page — it looked "frozen" when they came back. Now
  // losing focus shows a clear PAUSED card; one click resumes, and that click
  // also clears any movement key whose key-up was lost (otherwise you keep
  // walking), and closes a half-typed command prompt that would eat the keys.
  const PAUSE_CSS =
    '#demo-pause{position:fixed;inset:0;z-index:9998;display:none;align-items:center;justify-content:center;' +
      'background:rgba(3,4,8,.62);cursor:pointer;font-family:"GrandeRetro","GrandeTerm","Courier New",monospace;}' +
    '#demo-pause.on{display:flex;}' +
    '#demo-pause .dp-box{border:3px double #c9a227;background:#0b0e18;padding:18px 34px;text-align:center;color:#e8d9a8;}' +
    '#demo-pause .dp-t{font-size:clamp(20px,4vw,34px);color:#f1c84b;letter-spacing:.08em;}' +
    '#demo-pause .dp-s{margin-top:8px;font-size:clamp(11px,1.8vw,15px);color:#7dff9a;}';
  let pauseEl = null, pauseArmed = false;
  function resumeFromPause(e) {
    if (e) { e.preventDefault(); e.stopPropagation(); }
    if (pauseEl) pauseEl.classList.remove('on');
    try { window.focus(); } catch (err) {}
    try { if (window.engineClearKeys) window.engineClearKeys(); } catch (err) {}
    try {
      const inp = document.getElementById('input');
      if (inp && document.activeElement === inp && !inp.value.trim()) inp.blur();
    } catch (err) {}
  }
  function armFocusPause() {
    if (pauseArmed) return; pauseArmed = true;
    const st = document.createElement('style'); st.textContent = PAUSE_CSS; document.head.appendChild(st);
    pauseEl = document.createElement('div'); pauseEl.id = 'demo-pause';
    pauseEl.innerHTML = '<div class="dp-box"><div class="dp-t">PAUSED</div><div class="dp-s">\u25b6 click to resume</div></div>';
    document.body.appendChild(pauseEl);
    pauseEl.addEventListener('mousedown', resumeFromPause, true);
    pauseEl.addEventListener('click', (e) => { e.preventDefault(); e.stopPropagation(); }, true);
    // Only an EMBED needs this: a top-level window keeps its keys when you switch
    // back to the tab. Skip when a minigame overlay has focus (its iframe takes it).
    window.addEventListener('blur', () => {
      if (!IS_EMBEDDED) return;
      if (State.minigameActive) return;
      setTimeout(() => { if (!document.hasFocus()) pauseEl.classList.add('on'); }, 60);
    });
    window.addEventListener('focus', () => { try { if (window.engineClearKeys) window.engineClearKeys(); } catch (err) {} });
  }

  window.MMDemo = { gate };
})();
