#!/usr/bin/env python3
"""
STAMP-VERSION.PY - Writes config/site-version.js with a fresh version stamp (the current UTC time).

Run it from the site folder whenever you upload a new version of the site:
    python tools/stamp-version.py
(tools/build-search-index.py also runs it, so rebuilding the search index stamps a version too.)

When a returning visitor's browser sees a different stamp than last time, the retro desktop's
welcome tips, first-use hints, "Need a hand?" popup and the Scenemaker demo's tour all show
again, with a small note in the first tip explaining why (desktop/js/core/first-tips.js).
Upload config/site-version.js along with your other changed files.

It also refreshes the ?v=... fingerprints on each page's CSS/JS links (bust_caches), so visitors'
browsers pick up changed styles and scripts right away instead of showing a cached old copy.
"""
import datetime, glob, hashlib, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def stamp():
    v = datetime.datetime.now(datetime.timezone.utc).strftime('%Y.%m.%d-%H%M%S')
    out = os.path.join(ROOT, 'config', 'site-version.js')
    with open(out, 'w', encoding='utf-8') as f:
        f.write('/* SITE-VERSION.JS - generated by tools/stamp-version.py; a new stamp resets the tutorial tips. */\n')
        f.write(f"window.SITE_VERSION = '{v}';\n")
    print(f'Site version {v} -> {os.path.relpath(out, ROOT)}')
    return v

def bust_caches():
    """Add ?v=<fingerprint> to every local .css/.js link in the site's pages, so browsers (and
    Neocities' cache) fetch a file again only when it has actually changed."""
    pages = glob.glob(os.path.join(ROOT, 'pages', '*.html')) + [os.path.join(ROOT, 'index.html'), os.path.join(ROOT, 'not_found.html')]
    pat = re.compile(r'((?:src|href)=")(?!https?:|//|data:)([^"?#]+\.(?:css|js))(?:\?v=[0-9a-f]+)?(")')
    changed = 0
    for page in pages:
        if not os.path.exists(page):
            continue
        html = open(page, encoding='utf-8').read()
        base = os.path.dirname(page)
        def fix(m):
            target = os.path.normpath(os.path.join(base, m.group(2)))
            if not os.path.exists(target):
                return m.group(0)
            h = hashlib.md5(open(target, 'rb').read()).hexdigest()[:8]
            return f'{m.group(1)}{m.group(2)}?v={h}{m.group(3)}'
        new = pat.sub(fix, html)
        if new != html:
            open(page, 'w', encoding='utf-8').write(new)
            changed += 1
    print(f'Cache fingerprints refreshed in {changed} page(s)')

def page_versions():
    """Give every page a fingerprint of its own content (<meta name="page-version">) and list them all in
    config/page-versions.js. The Retro Desktop's browser compares the two: a page that doesn't match
    is an old copy stuck in the visitor's browser cache, so NetCrawler reloads it fresh. A page's
    fingerprint only changes when that page does, so unchanged pages never need re-uploading."""
    meta = re.compile(r'\s*<meta name="page-version" content="[0-9a-f]*">')
    versions = {}
    for page in sorted(glob.glob(os.path.join(ROOT, 'pages', '*.html'))):
        html = open(page, encoding='utf-8').read()
        clean = meta.sub('', html)
        h = hashlib.md5(clean.encode('utf-8')).hexdigest()[:8]
        new = clean.replace('<meta charset="UTF-8">', f'<meta charset="UTF-8">\n    <meta name="page-version" content="{h}">', 1)
        if new != html:
            open(page, 'w', encoding='utf-8').write(new)
        versions[os.path.basename(page)] = h
    out = os.path.join(ROOT, 'config', 'page-versions.js')
    body = ',\n'.join(f"    '{k}': '{v}'" for k, v in versions.items())
    with open(out, 'w', encoding='utf-8') as f:
        f.write('// GENERATED by tools/stamp-version.py (run by build-search-index.py): each page\'s content fingerprint.\n'
                '// NetCrawler uses it to spot an old copy of a page in the browser cache and reload it fresh.\n'
                'window.PAGE_VERSIONS = {\n' + body + '\n};\n')

if __name__ == '__main__':
    stamp()
    bust_caches()
    page_versions()
    bust_caches()      # again, so index.html picks up the new page-versions.js fingerprint
